services:
  database:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MARIADB_DATABASE=ilias
      - MARIADB_PASSWORD_FILE=/run/secrets/database_ilias_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/database_root_password
      - MARIADB_USER=ilias
    image: mariadb:10.8.2
    secrets:
      - database_ilias_password
      - database_root_password
    volumes:
      - ../database/backups:/var/backups/database
      - ../database/live:/var/lib/mysql
  ilias:
    depends_on:
      - database
    environment:
      - ILIAS_LUCENE_SEARCH=true
      - ILIAS_DATABASE_USER=ilias
      - ILIAS_DATABASE_DATABASE=ilias
      - ILIAS_DATABASE_PASSWORD_FILE=/run/secrets/database_ilias_password
      - ILIAS_HTTP_PATH=https://learn.medi.ch
      - ILIAS_ROOT_USER_PASSWORD_FILE=/run/secrets/ilias_root_password
      - ILIAS_SYSTEMFOLDER_CONTACT_FIRSTNAME=learn
      - ILIAS_SYSTEMFOLDER_CONTACT_LASTNAME=medi
      - ILIAS_SYSTEMFOLDER_CONTACT_EMAIL=martin.studer@medi.ch
      - ILIAS_COMMON_CLIENT_ID=medi01
    image: learn-medi-ilias/ilias:7.16-1
    secrets:
      - database_ilias_password
      - ilias_root_password
    volumes:
      - ../labor/skin_medi_ilias_7:/var/www/html/Customizing/global/skin/skin_medi_ilias_7
      - ../labor/contexts:/var/www/html/Customizing/global/contexts
      - ../data:/var/iliasdata
      - ../log:/var/log/ilias
  nginx:
    depends_on:
      - ilias
    image: learn-medi-ilias/nginx:7.16-1
    ports:
      - 127.0.0.11:80:80
    volumes:
      - ../labor/contexts:/var/www/html/Customizing/global/contexts
      - ../labor/skin_medi_ilias_7:/var/www/html/Customizing/global/skin/skin_medi_ilias_7
      - ../data/web:/var/iliasdata/web:ro
    environment:
      - ILIAS_COMMON_CLIENT_ID=medi01
  cron:
    depends_on:
      - ilias
    environment:
      - ILIAS_COMMON_CLIENT_ID=medi01
      - ILIAS_CRON_USER_PASSWORD_FILE=/run/secrets/ilias_cron_password
    image: learn-medi-ilias/cron:7.16-1
    secrets:
      - ilias_cron_password
    volumes:
      - ../data:/var/iliasdata
      - ../log:/var/log/ilias
  medi-course-management-backend:
    ports:
      - 127.0.0.1:81:9501
    image: medi-course-management/backend:1.5.0-3
    volumes:
      - ../labor/contexts/medi-course-management-backend/app:/app
    secrets:
      - ilias_api_password
    environment:
      FLUX_ILIAS_REST_API_CLIENT_PASSWORD_FILE: /run/secrets/ilias_api_password
      FLUX_ILIAS_REST_API_CLIENT_CLIENT: medi01
secrets:
  ilias_api_password:
    file: "../secrets/ilias_api_password"
  ilias_root_password:
    file: "../secrets/ilias_root_password"
  ilias_cron_password:
    file: "../secrets/ilias_cron_password"
  database_ilias_password:
    file: "../secrets/database_ilias_password"
  database_root_password:
    file: "../secrets/database_root_password"