version: '3.9'

services:
  nginx:
    depends_on:
      - ilias
    image: 'fluxms/flux-ilias-nginx:latest-ilias7.12'
    restart: unless-stopped
    ports:
      - 8080:80
  ilias:
    depends_on:
      - database
    image: 'fluxms/flux-ilias-php:php7.4-ilias7.12'
    restart: unless-stopped
    environment:
      - ILIAS_PHP_MEMORY_LIMIT=4096M
      - ILIAS_ROOT_USER_LOGIN=root
      - ILIAS_ROOT_USER_PASSWORD=homer
      - ILIAS_DATABASE_TYPE=innodb
      - ILIAS_DATABASE_DATABASE=ilias
      - ILIAS_DATABASE_USER=ilias
      - ILIAS_DATABASE_PASSWORD=ilias
      - ILIAS_SYSTEMFOLDER_CONTACT_FIRSTNAME=learn
      - ILIAS_SYSTEMFOLDER_CONTACT_LASTNAME=medi
      - ILIAS_SYSTEMFOLDER_CONTACT_EMAIL=support@learn.ch
      - ILIAS_CRON_USER_PASSWORD=ilias
      - ILIAS_LUCENE_SEARCH=true
      - ILIAS_HTTP_HTTPS_AUTODETECTION_HEADER_NAME=X-Forwarded-Proto
      - ILIAS_HTTP_HTTPS_AUTODETECTION_HEADER_VALUE=https
      - ILIAS_COMMON_SERVER_TIMEZONE=Europe/Zurich
      - ILIAS_STYLE_MANAGE_SYSTEM_STYLES=false
  cron:
    depends_on:
      - ilias
    image: 'fluxms/flux-ilias-cron:latest-ilias7.12'
    restart: unless-stopped
    environment:
      - ILIAS_COMMON_SERVER_TIMEZONE=Europe/Zurich
      - ILIAS_CRON_USER_PASSWORD=ilias
    secrets:
      - ilias-cron-password
  ilserver:
    depends_on:
      - database
      - ilias
    image: 'fluxms/flux-ilias-ilserver:java8-ilias7.12'
    restart: unless-stopped
    environment:
      - ILIAS_COMMON_SERVER_TIMEZONE=Europe/Zurich
      - ILIAS_ILSERVER_RAM_BUFFER_SIZE=512
      - ILIAS_ILSERVER_NIC_ID=7864
  database:
    image: mariadb:10.3.35-focal
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --sql-mode="IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=ilias
      - MARIADB_DATABASE=ilias
      - MARIADB_USER=ilias
      - MARIADB_PASSWORD=ilias