services:
  sftp:
    image: fluxms/flux-eco-sftp-sidecar:latest
    ports:
      - 10.100.12.192:2222:22
    volumes:
      - ../share/imports:/home/share
      - ../keys/sftp_share_imports:/etc/ssh/keys
    environment:
      - SFTP_SHARE_LOGIN_FILE=/run/secrets/sftp_share_login_imports
      - SFTP_SHARE_PASSWORD_FILE=/run/secrets/sftp_share_password_imports
    secrets:
      - sftp_share_login_imports
      - sftp_share_password_imports
  ilias:
    environment:
      - ILIAS_LUCENE_SEARCH=false
      - ILIAS_DATABASE_HOST=10.100.21.132
      - ILIAS_DATABASE_USER=ilias
      - ILIAS_DATABASE_DATABASE=ilias
      - ILIAS_DATABASE_PASSWORD_FILE=/run/secrets/database_ilias_password
      - ILIAS_HTTP_PATH=https://learn.medi.ch
      - ILIAS_ROOT_USER_PASSWORD_FILE=/run/secrets/ilias_root_password
      - ILIAS_SYSTEMFOLDER_CONTACT_FIRSTNAME=learn
      - ILIAS_SYSTEMFOLDER_CONTACT_LASTNAME=medi
      - ILIAS_SYSTEMFOLDER_CONTACT_EMAIL=learn@medi.ch
      - ILIAS_COMMON_CLIENT_ID=medi01
      - ILIAS_SMTP_HOST=server2.ahja.ch
      - ILIAS_SMTP_PORT=587
      - ILIAS_SMTP_ENCRYPTION=tls
      - ILIAS_SMTP_USER_FILE=/run/secrets/ilias_smtp_user
      - ILIAS_SMTP_PASSWORD_FILE=/run/secrets/ilias_smtp_password
      - ILIAS_LANGUAGE_DEFAULT_LANGUAGE=de
      - ILIAS_LANGUAGE_INSTALL_LANGUAGES=en de fr
      - ILIAS_LANGUAGE_INSTALL_LOCAL_LANGUAGES=en de fr
      - ILIAS_HTTP_HTTPS_AUTODETECTION_HEADER_NAME=X-Forwarded-Proto
      - ILIAS_HTTP_HTTPS_AUTODETECTION_HEADER_VALUE=https
    image: learn-medi-docker-ilias/ilias:2023-05-09-1
    secrets:
      - database_ilias_password
      - ilias_root_password
      - ilias_smtp_user
      - ilias_smtp_password
    volumes:
      - ../iliasdata-web:/var/iliasdata/web
      - ../iliasdata:/var/iliasdata
      - ../log:/var/log/ilias
  nginx:
    depends_on:
      - ilias
    image: learn-medi-docker-ilias/nginx:2023-05-09-1
    ports:
      - 10.100.12.192:80:80
    volumes:
      - ../iliasdata-web:/var/iliasdata/web:ro
  cron:
    depends_on:
      - ilias
    entrypoint: /flux-ilias-ilias-base/bin/cron.sh
    init: true
    environment:
      - ILIAS_COMMON_CLIENT_ID=medi01
      - ILIAS_CRON_USER_PASSWORD_FILE=/run/secrets/ilias_cron_password
    image: learn-medi-docker-ilias/ilias:2023-05-09-1
    secrets:
      - ilias_cron_password
    volumes:
      - ../iliasdata-web:/var/iliasdata/web
      - ../iliasdata:/var/iliasdata
      - ../log:/var/log/ilias
secrets:
  ilias_root_password:
    file: "../secrets/ilias_root_password"
  ilias_cron_password:
    file: "../secrets/ilias_cron_password"
  database_ilias_password:
    file: "../secrets/database_ilias_password"
  sftp_share_login_imports:
    file: "../secrets/sftp_share_login_imports"
  sftp_share_password_imports:
    file: "../secrets/sftp_share_password_imports"
  ilias_smtp_user:
    file: "../secrets/ilias_smtp_user"
  ilias_smtp_password:
    file: "../secrets/ilias_smtp_password"
